name: Frontend Security Analysis Reports

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  security-reports:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        continue-on-error: true

      # Run tests with coverage
      - name: Run tests with coverage
        run: npm run test:coverage
        continue-on-error: true
        
      # SAST Analysis with SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=shopsmartsg
            -Dsonar.projectKey=ShopSmartSG_frontend
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.coverage.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx,src/reportWebVitals.js,src/index.js
        continue-on-error: true

      # Linting Report
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      # DAST Analysis with OWASP ZAP
      - name: Start frontend application
        run: |
          npm run build
          npm install -g serve
          serve -s build -l 3000 &
          sleep 10
        continue-on-error: true

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:3000'
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: '-t http://localhost:3000 -r zap_report.html'
        continue-on-error: true
          
      # Upload all reports as artifacts
      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()  # This ensures reports are uploaded even if previous steps fail
        with:
          name: security-reports
          path: |
            zap_report.html
            coverage/
            eslint_report.json